### ISSUE TITLE
yaws no longer works as rebar dependency

### ISSUE THREAD

**Issue by marcsugiyama** [erlyaws/yaws#178]
rebar looks for .app and .app.src files.  The yaws.app.src is now yaws.app.src.in, so rebar fails with:

DEBUG: is_app_available, looking for App yaws with Path "/Users/sugiyama/work/git/clones/flowforwarding/loom/tapestry/deps/yaws"
WARN:  Expected /Users/sugiyama/work/git/clones/flowforwarding/loom/tapestry/deps/yaws to be an app dir (containing ebin/*.app), but no .app found.
ERROR: Dependency dir /Users/sugiyama/work/git/clones/flowforwarding/loom/tapestry/deps/yaws failed application validation with reason:
{missing_app_file,"/Users/sugiyama/work/git/clones/flowforwarding/loom/tapestry/deps/yaws"}.

Works with yaws-1.98.

**Comment by nbrady-techempower** [comment]
Hi @vinoski, I was wondering what release this fix was put into and if it still applies. It seems as though I'm having exactly the same problems on all versions I've tried.

**Comment by vinoski** [comment]
@nbrady-techempower: the fix is in Yaws 1.99 and newer. You might want to check the version of `rebar` you're using, as different versions have had issues with this sort of thing over the years. I believe 2.6.1 is the latest released version of `rebar`.

**Comment by nbrady-techempower** [comment]
@vinoski Ah, always when I'm looking in the wrong place. Was part of the enterprise version of erlang I was using. Thanks so much!
