### ISSUE TITLE
Unknown error kills yaws?

### ISSUE THREAD

**Issue by chomwitt** [erlyaws/yaws#281]
I've started yaws interactively and i notice  that error that displays for no apparent reason every minute.
Yaws seem that is running ok though. What does it come from and why yaws seems to not have stoped and have the same pid from starrt( checked with self(). ?

=ERROR REPORT==== 31-Jul-2016::03:57:10 ===
Yaws process died: {stream_timeout,
                       [{yaws_server,stream_loop_send,5,
                            [{file,"yaws_server.erl"},{line,2967}]},
                        {yaws_server,aloop,4,
                            [{file,"yaws_server.erl"},{line,1215}]},
                        {yaws_server,acceptor0,2,
                            [{file,"yaws_server.erl"},{line,1052}]},
                        {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,237}]}]}

**Comment by vinoski** [comment]
Are you using Yaws streaming from one of your applications or from one of the Yaws examples such as `stream.yaws` or `urandom.yaws`? The `yaws_server:stream_loop_send/5` call occurs in `aloop` only when an `out/1` handler returns a `streamcontent` directive or the like to Yaws.
