### ISSUE TITLE
mime types for .wasm

### ISSUE THREAD

**Issue by baryluk** [erlyaws/yaws#413]
Hi,

it would be nice if yaws supported mime type for WASM files.

This is because https://www.w3.org/TR/wasm-web-api-1/#streaming-modules , for streaming compilation (that is compiling as the data are being received from server), requires mime type to be set properly. Otherwise, a code can't use that functionality, and need to fall back to fetching whole file, putting it into JS `ArrayBuffer` and compiling manually - all of which is undesirable - adds latency, adds memory usage, adds extra code.

I don't see wasm on https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types or https://www.iana.org/assignments/media-types/media-types.xhtml

but usually:

```
application/wasm   .wasm
```

There are also `.wat` and `.wast` , files which are similar, and are a text representations of .wasm files, they can be produced by compilers, or written by hand, and then assembled into `.wasm`, or `.wasm` can be decompiled into them. I don't know what mime types they do have (some people propose `text/webassembly`, but I don't think it is wide spread or standarized). They are useful during development and debugging.

https://github.com/WebAssembly/design/issues/981 for a bit of extra context.

**Comment by vinoski** [comment]
In the `fix-413` branch I've added the `wasm` MIME type, but I'm hesitant to add `wat` or `wast` MIME types as it's not clear, even after searching around quite a bit for them, that these are as widely adopted as the `wasm` type.

**Comment by baryluk** [comment]
Excellent. That is all really needed. Thank you!

**Comment by vinoski** [comment]
@baryluk Thanks for raising this issue and verifying that the proposed fix is adequate. The fix is now on the `master` branch.
