### ISSUE TITLE
Crash when operating on closed socket

### ISSUE THREAD

**Issue by etnt** [erlyaws/yaws#416]
https://github.com/erlyaws/yaws/blob/d7a819d698b30982867ce6862b1d579a7a4c23b0/src/yaws_server.erl#L1190

In HTTP/1.1 Connection `keep-alive` is the default (in HTTP/1.0 it is not), so after serving a request, Yaws enters the `aloop` again where we call `yaws:http_get_headers/2` which may crash with a `badmatch` down in the `yaws:setopts` function if the Client is gone and the socket is closed. 

This can of course be avoided if the Client is kind enough to send a header `Connection: close` , but when this is not the case it will cause a crash in the Yaws server which is a bit unfortunate (and ugly). 

So perhaps this call to `yaws:http_get_headers/2` should be guarded from this to happen (e.g we do a catch around the `aloop` call in the `acceptor0/2` function) ?

**Comment by vinoski** [comment]
Good idea, there's no point in crashing at that spot.

**Comment by vinoski** [comment]
Unfortunately our Travis-CI support seems to have finally run out, so I merged this without checking it on all supported platforms. But it's pretty straightforward and so should be ok.
