### ISSUE TITLE
Support for a deterministic build option

### ISSUE THREAD

**Issue by TD5** [erlyaws/yaws#433]
Hi, thanks for all the fantastic work on the `yaws` project!

### Context
I am trying to improve the build determinism of my project, so that the output I get from the build process is the same, no matter where I build it.

I set `{erl_opts, [deterministic]}` via my `rebar3` config for my own code and my dependencies, and for most of them it works nicely, and I don't see things like absolute paths from my build machine in the resulting `.beam` files. `yaws` is a bit more complicated, I think, because it uses the `rebar-pre-script`. In particular, `gen-yaws-generated` bakes-in some paths from the build environment (`etcdir` & `vardir`), which are then [sometimes used to locate config](https://github.com/erlyaws/yaws/blob/b49e75dc81fa3312542fcee886a2b94288e75608/src/yaws_config.erl#L39).

### Request
Is there a way to prevent absolute paths which are specific to my build machine leaking during the build process? If not, is it possible to add a way to do that, e.g. by creating some new option or by piggy-backing on the [`deterministic` flag](https://erlang.org/doc/man/compile.html#exports) to switch the behaviour?

**Comment by vinoski** [comment]
Primary support for rebar3 is still on our `rebar3-support` branch, so hopefully you're using that. (It unfortunately still needs work; we can build Yaws ok with that branch, but it still can't run the testsuite, and it won't be merged until it can.)

One way to help move your request along would be to provide a list of non-deterministic paths that you see from a build. If such data involves private aspects that you'd rather not publish here, feel free to email it to me directly at my ieee.org address.

**Comment by TD5** [comment]
Yes, sorry, I should have stated that I am using the `rebar3-support` branch.

The paths are `%VARDIR%` and `%ETCDIR%` used by `yaws_generated.template`/`yaws_generated.erl` [here](https://github.com/erlyaws/yaws/blob/master/src/yaws_generated.template#L19), which come from [`YAWS_DIR`](https://github.com/erlyaws/yaws/blob/master/scripts/rebar-pre-script#L10), which comes [from the location of the build script](https://github.com/erlyaws/yaws/blob/master/scripts/rebar-pre-script#L4).

When I say they're "non-deterministic", I mean that insofar as I could build `yaws` in two different directories, and the resulting `.beam` file would change, because those directories get baked into the `.beam` files. In my use-case, for reproducibility reasons, I'd like the generated `.beam` files to be identical, regardless of the absolute path I happened to build them in. I think that would mean having an option to not store these paths in `yaws_generated` at all.

Does that make sense?

**Comment by vinoski** [comment]
We can indeed make `vardir()` and `etcdir()` return `undefined` if, say, the environment variable `YAWS_DETERMINISTIC_BUILD` is set. But in this case, the user will need to ensure that `application:get_env(yaws, config)` returns the full pathname of the `yaws.conf` file, otherwise there's a chance Yaws won't be able to find it. I think that's a reasonable trade-off, do you agree?

**Comment by vinoski** [comment]
I pushed branch `fix-433` to github. It's branched off `rebar3-support`. Please give it a try @TD5 and let me know if it addresses the issue.

**Comment by TD5** [comment]
Thanks, @vinoski. I'll take a look 👍

**Comment by TD5** [comment]
@vinoski I haven't tried wiring everything up end-to-end, but I did build this branch with and without `YAWS_DETERMINISTIC_BUILD` being set, and I can confirm that the environment variable does prevent the hardcoding of paths as hoped, so this source of non-determinism does seem to be resolved 👍 Thanks!

**Comment by vinoski** [comment]
Great, thanks for trying it out! I'll get it merged.

**Comment by vinoski** [comment]
This change is now on master and rebar3-support.
