### ISSUE TITLE
Yaws assumes `error_logger` process always exists and it is a gen_event

### ISSUE THREAD

**Issue by seriyps** [erlyaws/yaws#442]
I noticed that in `yaws_log` it is assumed that there is always a process registered as `error_logger` and this process is `gen_event`:

https://github.com/erlyaws/yaws/blob/866714d3de230ba73ab7455aa9a9d70079429a87/src/yaws_log.erl#L363-L368

https://github.com/erlyaws/yaws/blob/866714d3de230ba73ab7455aa9a9d70079429a87/src/yaws_log.erl#L398

But with OTP-21 logger one can have just a custom OTP logger handler registered as `error_logger` which would capture all the `error_logger:*_msg` `error_logger:*_report` logs without ever starting any processes with `error_logger` name.

I think it might make sense to, maybe, add some config that tells Yaws to not try to manage the `error_logger`?

**Comment by vinoski** [comment]
In general, Yaws logging needs work, as it's never been converted over to `logger`. With the recent Yaws 2.1.0 release, the oldest Erlang/OTP release we now support is 21.0, which is when `logger` was introduced, so Yaws should now just drop older logging support and convert fully to `logger`.

**Comment by seriyps** [comment]
Thanks.
I can try to have a look and maybe send some pull-request to migrate to OTP logger.

What degree of backwards-compatibility should we have? May you point me if there is some documentation describing public logging-related APIs which we should not break?

**Comment by seriyps** [comment]
I guess might be nice to keep `yaws_logger` behaviour, but that may require a special `logger_handler` for "virtual servers" which requested a custom `logger_mod`.

Maybe install individual logger handler for each enabled `auth_log` and `access_log`.

Some docs I found:
https://github.com/erlyaws/yaws/blob/866714d3de230ba73ab7455aa9a9d70079429a87/doc/yaws.tex#L2005-L2023

http://yaws.hyber.org/logger_mod.yaws

**Comment by seriyps** [comment]
Actually, it seems the better plan would be:

* keep the yaws_logger as is
* update the `yaws_log` (default implementation of `yaws_logger` behaviour) to be a tiny wrapper over `logger:add_handler` `logger:remove_handler` `logger:log` with `logger_std_h` with custom formatter.
* remove `yaws_log_file_h`

**Comment by vinoski** [comment]
Yep, that sounds right.

**Comment by seriyps** [comment]
Ok, pushed a bit different implementation from what I planned, see #443

**Comment by seriyps** [comment]
Fixed by #445
