### ISSUE TITLE
JSON-RPC payloads don't need urldecode step

### ISSUE THREAD

**Issue by cl0ne** [erlyaws/yaws#449]
For 14 years [due to problems with some JS library](https://sourceforge.net/p/erlyaws/mailman/erlyaws-list/thread/a08fff5f0712301707o4149d110y28105a1a07911c07%40mail.gmail.com/) (5749449e567f2a0bfc25a47190e0310332963cc5) JSON-RPC request handler expects payload to be URL encoded.

[JSON-RPC specification](https://www.jsonrpc.org/specification) doesn't even mention the need for percent-encoding at all (same goes for [older spec](https://www.jsonrpc.org/specification_v1)). None of the popular JSON-RPC clients (at least, this applies to Perl, C#, Java, Python implementations) apply URL encoding to the produced JSON request. Consequently, any method parameter that contains percent symbol will be either decoded to a wrong value, or will more often cause request handling failure.

[The example](http://yaws.hyber.org/json_sample.html) from "[AJAX through JSON-RPC](http://yaws.hyber.org/json_intro.yaws)" documentation page is broken due to this issue as well. Just include percent symbol in any of the submitted arguments, and you'll get either response code 500 (when the resulting character sequence is not valid, e.g. `hello%world`), or received request with different argument values (e.g., `hello%20world` becomes `hello world`).

This can hardly be expected as a correct behaviour for JSON-RPC server, even though correcting it is a backwards-incompatible change.

**Comment by vinoski** [comment]
Thanks for the explanation. I agree the current code is incorrect, and given the lack of complaints about it, I think it will be OK in this case to break backwards-compatibility in favor of correct behavior.
