### ISSUE TITLE
Error on launch application Yaws 

### ISSUE THREAD

**Issue by gvsafronov** [erlyaws/yaws#454]
Hello!

I use Manjaro Linux Operating System.
When I am startting build after compilation from source a see the nex error message:

Mokachi@/home/grigoriy/yaws >./yaws start
cat: /home/grigoriy/yaws/rel/releases/start_erl.data: No such file or directory
./yaws: line 119: /home/grigoriy/yaws/rel/erts-/bin/escript: No such file or directory
./yaws: line 164: /home/grigoriy/yaws/rel/erts-/bin/run_erl: No such file or directory

Erlang/OTP 24 version: 24
Eshell version: V12.3.2

What am I doing wrong?
Thank you.

**Comment by vinoski** [comment]
Can you show your build commands? Also, are you building from master, or from a tag?

**Comment by gvsafronov** [comment]
My build commands:
1. Mokachi@/home/grigoriy/yaws > autoreconf -fi
2. Mokachi@/home/grigoriy/yaws >./configure 
3. Mokachi@/home/grigoriy/yaws >make

I'm building from master.

**Comment by gvsafronov** [comment]
I run **make install**  and then yaws-started successfully!
I'am much obliged to you!
