### ISSUE TITLE
Do not make fatal inaccessible log file

### ISSUE THREAD

**Issue by ignatenkobrain** [erlyaws/yaws#473]
Hello,

We're using yaws in our project and we've recently upgraded from 2.0.6 to 2.1.1 (yes, we are late). That causes one annoying issue for us: when logdir does not exist, or has wrong permissions, the start of our application fails:

```erlang
** Generic server yaws_log terminating 
** Last message in was {setup,
                           {gconf,"/usr/lib64/erlang/lib/yaws-2.1.1",false,
                               100,"/mnt/log/gcf/gcfp",
                               ["/usr/lib64/erlang/lib/yaws-2.1.1/examples/ebin"],
                               [],[],30000,nolimit,400,1000000,8000,nolimit,
                               [],10240,[],1000000,0,
                               ["/usr/lib64/erlang/lib/yaws-2.1.1/examples/include"],
                               "/usr/bin/php-cgi","Yaws 2.1.1",
                               gcfp@5659a7dbc477,false,[],8,undefined,
                               [inet],
                               yaws_session_server,undefined,120000,3600000,
                               disable},
                           [[{sconf,10010,4103,[],undefined,undefined,
                                 "/var/gdc/gcf/gcfp",[],
                                 {0,0,0,0},
                                 "5659a7dbc477:10010",[],undefined,undefined,
                                 undefined,
                                 [{"/var/gdc/gcf/gcfp",[]}],
                                 nolimit,
                                 [{"/",gcfp_rest_api}],
                                 [],yaws_outmod,yaws_outmod,yaws_outmod,yaws,
                                 yaws_log,undefined,undefined,
                                 [yaws,php,cgi,fcgi],
                                 [],
                                 ["index.yaws","index.html","index.php"],
                                 [],
                                 [{listen_opts,[{backlog,1024}]}],
                                 [],undefined,undefined,
                                 {cgi,"/usr/bin/php-cgi"},
                                 undefined,undefined,undefined,undefined,[],
                                 undefined}]]}
** When Server state == {state,false,undefined,
                               ["[","03","/","Aug","/","2023",":","13",":",
                                "41",":","21"," ",
                                [43,"02","00"],
                                "]"],
                               1000000,undefined,false}
** Reason for termination ==
** {{badmatch,
        {error,
            {handler_not_added,
                {open_failed,"/mnt/log/gcf/gcfp/report.log",enoent}}}},
    [{yaws_log,handle_call,3,[{file,"yaws_log.erl"},{line,177}]},
     {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
** Client yaws_server stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,214}]},
    {gen_server,call,3,[{file,"gen_server.erl"},{line,243}]},
    {yaws_server,init2,5,[{file,"yaws_server.erl"},{line,238}]},
    {yaws_server,handle_call,3,[{file,"yaws_server.erl"},{line,300}]},
    {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},
    {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},
    {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]
```

In older version, just the warning was shown but the whole initialization continued.

Would you have some suggestion how to make it behave similar to the old version?

Thank you in advance!

**Comment by vinoski** [comment]
What version of OTP are you using?

When this error occurs, does the `/mnt/log/gcf/gcfp` directory already exist? I tried removing `report.log` for my yaws instance and it was recreated after restarting yaws, so I suspect in your case the logging directory doesn't exist.

**Comment by ignatenkobrain** [comment]
Hello @vinoski! We are using OTP 24.3.

The `/mnt/log/gcf/gcfp` directory does not exist and the application runs from non-root user so even if it would exist, it would get permission denied when trying to create files.

In production, it works fine as we have all directories set and such. However, in testing environment (where we don't care about these logs), previously it was simply not logging to the file while now it crashes our application on start.

**Comment by vinoski** [comment]
This is almost certainly due to the switchover to the OTP  21 Logger about 5 years ago.

For your testing environment, can you configure your yaws logging directory to `/tmp` or similar?

**Comment by alexandrkirilov** [comment]
Tried to run application under root permission and under the non-root. It's happening ONLY on Ubuntu. On MacOS and FreeBSD all is Ok.

**Comment by alexandrkirilov** [comment]
Here the log from MacOS

``
$ yaws
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] [dtrace]

=INFO REPORT==== 16-Oct-2023::23:20:15.171274 ===
Yaws: Using config file /usr/local/Cellar/yaws/2.1.1/etc/yaws/yaws.conf

Eshell V14.0.2 (press Ctrl+G to abort, type help(). for help)
=ERROR REPORT==== 16-Oct-2023::23:20:15.172339 ===
Config Warning: Directory /usr/local/Cellar/yaws/2.1.1/lib/yaws/examples/include for include_dir doesn't exist

=INFO REPORT==== 16-Oct-2023::23:20:15.258318 ===
Yaws: Using global subconfig file /Users/alexandr/Tools/Yaws/ExtendedConfig/host1.conf

=INFO REPORT==== 16-Oct-2023::23:20:15.258848 ===
Yaws: Using global subconfig file /Users/alexandr/Tools/Yaws/ExtendedConfig/host2.conf

=INFO REPORT==== 16-Oct-2023::23:20:15.285869 ===
Ctlfile : /Users/alexandr/.yaws/yaws/default/CTL

=INFO REPORT==== 16-Oct-2023::23:20:15.411639 ===
Yaws: Listening to 0.0.0.0:8888 for <1> virtual servers:
 - http://*:8888 under undefined

=INFO REPORT==== 16-Oct-2023::23:20:15.415233 ===
Yaws: Listening to 0.0.0.0:8000 for <2> virtual servers:
 - http://*:8000 under /usr/local/Cellar/yaws/2.1.1/var/yaws/www
 - http://localhost:8000 under /private/tmp

=INFO REPORT==== 16-Oct-2023::23:20:15.415478 ===
Yaws: Listening to 0.0.0.0:7777 for <1> virtual servers:
 - http://*:7777 under undefined

=INFO REPORT==== 16-Oct-2023::23:20:15.429473 ===
Yaws: Listening to 0.0.0.0:4443 for <1> virtual servers:
 - https://*:4443 under /private/tmp
 ``

**Comment by alexandrkirilov** [comment]
On MacOS Erlang and Yaws installed with brew

**Comment by vinoski** [comment]
Looks like Ubuntu sets `log_wrap_size` to 0 in `/etc/yaws/yaws.conf` in an attempt to turn off log rotation, which should be valid, but this crashes the Erlang/OTP `logger_std_h` because it doesn't allow its `max_no_bytes` setting to be 0. For no rotation, it should be set to `infinity`, but this can't be achieved via `yaws.conf` because it only allows integers for this setting.

As a workaround, try setting `log_wrap_size` in `/etc/yaws/yaws.conf` on Ubuntu to an integer value like 1000000, which is the Yaws default, or some other integer value of your choosing.

**Comment by alexandrkirilov** [comment]
@vinoski Thx a lot. It works for me on Ubuntu 22.04.
